spring:
  datasource:
    ifland:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ifland_dic?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: yun0587

  # JPA 설정
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: true
        format_sql: true    # 권장되지 X
        use_sql_comments: true
        use-new-id-generator-mappings: false
    hibernate:
      ddl-auto: none

  # Thymeleaf 설정
  thymeleaf:
    check-template-location: true   # 해당 위치에 파일이 있는지 참조
    cache: false    # 캐시를 남기지 않음

# Mybatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:/mapper/sql/*.xml
  config-location: classpath:/mapper/config/mybatis-config.xml

# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace